x-php: &php
  image: pimcore/pimcore:php8.1.17-v1.3
  environment:
    MYSQL_DATABASE: 'pimcore_test'
  volumes:
    - ./:/var/www/html

services:
  database:
    profiles: [ test, dev ]
    image: mariadb:10.5.13
    command: >-
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      # must fit with .github/workflows/test-and-qa.yaml
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'pimcore_test'
      MYSQL_PASSWORD: 'pimcore'
      MYSQL_USER: 'pimcore'
    tmpfs:
      - /tmp
      - /var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s

  init:
    <<: *php
    profiles: [ init ]
    command: composer install

  test:
    <<: *php
    profiles: [ test ]
    command: composer test
    depends_on:
      database:
        condition: service_healthy

  php-cs-fixer:
    <<: *php
    profiles: [ php-cs-fixer ]
    command: composer cs:fix

  phpstan:
    <<: *php
    profiles: [ phpstan ]
    command: composer phpstan
