services:
  db:
    image: 'mariadb:10.10.2'
    environment:
      MYSQL_ROOT_PASSWORD: 'pimcore'
      MYSQL_DATABASE: 'pimcore_test'
      MYSQL_USER: 'pimcore'
      MYSQL_PASSWORD: 'pimcore'

  php:
    image: 'pimcore/pimcore:PHP8.1-cli'
    working_dir: '/app'
    volumes:
      - './:/app'
